P1: 200.0
P2: 400.0
correlation_window_size: 15
disp12MaxDiff: 0
disparity_range: 128
fullDP: false
id: 0
min_disparity: 80
parent: 0
prefilter_cap: 31
prefilter_size: 9
speckle_range: 4
speckle_size: 421
state: true
stereo_algorithm: 0
texture_threshold: 264
type: ''
uniqueness_ratio: 2.0